services:
  app:
    build: .
    ports:
      - "5001:5001"
    # depends_on:
    #   - memgraph

  # memgraph:
  #   image: memgraph/memgraph-mage
  #   ports:
  #     - "7687:7687"
  #     - "7444:7444"
  #   volumes:
  #     - memgraph_data:/var/lib/memgraph

  # memgraph_lab:
  #   image: memgraph/lab
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - memgraph
  #   environment:
  #     QUICK_CONNECT_MG_HOST: host.docker.internal

# volumes:
#   memgraph_data: